openapi: 3.0.0
info:
  version: 1.0.0
  title: Local Twitch Chatbot
servers:
  - url: 'http://localhost:5000/api/v1'
paths:
  /commands:
    get:
      summary: 'Get a list of all commands'
      operationId: getAllCommands
      tags:
        - commands
      responses:
        '200':
          description: 'A list of commands'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllCommands'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Command:
      type: object
      properties:
        id:
          type: integer
          format: int32
        command:
          type: string
        response:
          type: string
        used:
          type: integer
          format: int32
    AllCommands:
        type: array
        items:
            $ref: '#/components/schemas/Command'
    Error:
      type: object
      properties:
        error:
          type: string